Console Error
AuthSessionMissingError: Auth session missing!

Call Stack
4

<unknown>
file:///home/user/studio/.next/static/chunks/node_modules_%40supabase_auth-js_dist_module_33324aae._.js (2499:32)
SupabaseAuthClient._useSession
file:///home/user/studio/.next/static/chunks/node_modules_%40supabase_auth-js_dist_module_33324aae._.js (2379:26)
async SupabaseAuthClient._getUser
file:///home/user/studio/.next/static/chunks/node_modules_%40supabase_auth-js_dist_module_33324aae._.js (2487:20)
async
file:///home/user/studio/.next/static/chunks/node_modules_%40supabase_auth-js_dist_module_33324aae._.js (2474:20)